/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "aahmextmrawzcsqdpeyp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhaG1leHRtcmF3emNzcWRwZXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2Mjk1MTksImV4cCI6MjA4MjIwNTUxOX0.Xa6eii-vj2KQFEtxpeXRAbYIVF-C1NDL588EL-AqvdA"